while(($inp = Read-Host -Prompt "Run Script? 'N' will exit") -ne "N"){
    $computer = (Read-Host "Computer name")

    Write-Host 'confirmed'
    New-PSSession -computer $computer

    Invoke-Command -computer $computer -FilePath .\Script\ScriptAddLocalAdmin.ps1
    Remove-PSSession -computer $computer

}
# SIG # Begin signature block
# MIIJYQYJKoZIhvcNAQcCoIIJUjCCCU4CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUuxUD1g2fRJ+EYmCKOWzvPDBr
# qQKgggbIMIIGxDCCBKygAwIBAgITGgAAAKsOTLtZonR10AAAAAAAqzANBgkqhkiG
# 9w0BAQ0FADBLMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxGDAWBgoJkiaJk/IsZAEZ
# FghnYXRld2F5MjEYMBYGA1UEAxMPZ2F0ZXdheTItREMxLUNBMB4XDTIwMDMzMDE4
# NTMzN1oXDTIyMDMzMDE5MDMzN1owXzEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRgw
# FgYKCZImiZPyLGQBGRYIZ2F0ZXdheTIxFjAUBgNVBAsMDXhfUkFNQ08gVXNlcnMx
# FDASBgNVBAMTC1phY2sgQWNrbGluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
# CgKCAQEAyqxi1+VWYCKKnVJJUitGku9RmlelOhbrUqzfd5iKJyHiX/xdZ4tBlPbx
# SBmK7y3gY37dnWy5r1ldK8/91DHuNDJ3ZWeJzz4WHsxPRXqM0hsRXVBQ8JzOtWq+
# v2Jr1UeZvTt97LFBs6BhfE0NGU4M9dYxzLiiNoq9w6P3NNDrmKn0Sri7MkMGpiml
# ZK/T5stNL0Hu/DQWInvMHXonUlm/CB1XUqandwY8nD7vBLdLlChzcpj1ohADt0wN
# h1y/OD7WfVrSARL6pBuDKC2M+bSXn6QH34IDQoQqA5/Nmbt6HfJJqW94fSAZQIi/
# uWy3rljxGEKa8pJPcoPlEuBEqzMhJQIDAQABo4ICizCCAocwPAYJKwYBBAGCNxUH
# BC8wLQYlKwYBBAGCNxUIg9eWden/aIT1kSeHi9Qggb3FWCSDvudQgofITgIBZAIB
# AzATBgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwGwYJKwYBBAGC
# NxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUff4W+40vEksxMH/vm1yPd3xn
# gSgwHwYDVR0jBBgwFoAU3+5/2AdRzcHHVJLRSfrYln47fpUwgcwGA1UdHwSBxDCB
# wTCBvqCBu6CBuIaBtWxkYXA6Ly8vQ049Z2F0ZXdheTItREMxLUNBLENOPWRjMSxD
# Tj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049
# Q29uZmlndXJhdGlvbixEQz1nYXRld2F5MixEQz1sb2NhbD9jZXJ0aWZpY2F0ZVJl
# dm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9p
# bnQwgcQGCCsGAQUFBwEBBIG3MIG0MIGxBggrBgEFBQcwAoaBpGxkYXA6Ly8vQ049
# Z2F0ZXdheTItREMxLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
# cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWdhdGV3YXkyLERDPWxv
# Y2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9u
# QXV0aG9yaXR5MC8GA1UdEQQoMCagJAYKKwYBBAGCNxQCA6AWDBRaYWNrQUByYW1j
# b21wYW55LmNvbTANBgkqhkiG9w0BAQ0FAAOCAgEAJD+HJbjHz6ofuc6evcAKOarY
# xjYosU9lh6bxjGERtqhkTYwNGdq+JN5HiPFb/rH0slUP31TS3VCjGzB2AUOnKgAC
# //1/nInKZe1vKtbD0UohcvHgSBryvzcoVFtybmJgH87vKGNuzO3WRQWEGDTwXz6b
# hIx+alReoCrQEmuoC5B6jGuNRDV7ZcOkgwEUVlKLPBQ5MfwoDcO3dsXpXwQWweh4
# X/HWk4Osn4dyCW25XuBi9xMXduphyI3qDInLa7cMkdX3k7Mq8qqb35voLGeKYQbi
# 1RYSCjHeoHYVNNctdw/GBS4TccSr0pdfDRhHey08/wm4rSDQOed4T4cmTrtLly9s
# mvh39eCGXIfr6oh9QLBrvrIoSgCeDpl3T0Oc0cuJUIS04sWUyDkiWGwk2vSDsbma
# VS/cv/4Ghvn0sVT6vaOrHfo3J/adU2KUuMmCWF0tz2zSmF03RoqGmhq1Zrur5Wkz
# rkWNSD/GRldI5BIHzGZCo9/B61WtFESEsq57YzUuqTRkhZqeTdncPwMd7OenxanK
# YYmI7ohaMlD8hkF/4nbNQQUmaiAagPZ7WEeo5ITnFasvc+1r0ypNSjPV0Hi3jBiT
# eVQYWeBuG9btHcZ4j0hgH1lInrfKXL8SY1bafB3Z+0knowfwld7mrdYRYLbeSQPL
# 9K2lx6N9socYOTOdYh4xggIDMIIB/wIBATBiMEsxFTATBgoJkiaJk/IsZAEZFgVs
# b2NhbDEYMBYGCgmSJomT8ixkARkWCGdhdGV3YXkyMRgwFgYDVQQDEw9nYXRld2F5
# Mi1EQzEtQ0ECExoAAACrDky7WaJ0ddAAAAAAAKswCQYFKw4DAhoFAKB4MBgGCisG
# AQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFKvG
# mKelEIY/kT9YJ5neiJQs1cV9MA0GCSqGSIb3DQEBAQUABIIBADEgbu61lvlI+WIQ
# oYFJoWKpLa2KuOJE3h7Zd0cIQaSqCDuBlLZLAZyuMXhkY0GvGjHHXt9nXFpMLPsn
# CCwA9pIQUauVpTGIcsd81t3pS+lS9vANVI/zhfpN8bL5wcYbT9JwOzItj9Fo0KDN
# fyD2++CJnrPjr87qO+OMJt8zaY/YGxBIUnorJM/NxFrh6yaOOpU7VZV0jXZUxb7/
# LBIV9cpZbA0iC+8sD1EUiYa3Dt/1XF8zMEpGcOo/5rd1D6BYcwOMUdDSjn4Uy3mU
# i5NzqLb/zXB9HkfxhMW9vCG6v3SLtmWqY1mYYnzgsV8DoRRyOgbka7MWtioGwZ3B
# XWbGnyY=
# SIG # End signature block
