$group = 'Administrators'
$user = (Read-Host "User Login Name")
$computer = $env:COMPUTERNAME
$title    = 'Remove Administrator Rights'
$question = "Are you sure you want to proceed? 
Computer: $computer   
User: $user"
$choices  = '&Yes', '&No'

$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 0) {

$isInGroup = (Get-LocalGroupMember $group).Name -contains "gateway2\$user"
write-host $isInGroup
if ($isInGroup -ne 'True') {
    
    try {
    Add-LocalGroupMember -Group $group -member $user
    write-host 'User Added'
    }
    Catch {
    write-host 'Error: User not added'
    }

} else {
    Write-Host 'Not local Admin'
}
}
# SIG # Begin signature block
# MIIJYQYJKoZIhvcNAQcCoIIJUjCCCU4CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUoA+hnZnb3HH8NMqX2j2RjJZR
# LRCgggbIMIIGxDCCBKygAwIBAgITGgAAAKsOTLtZonR10AAAAAAAqzANBgkqhkiG
# 9w0BAQ0FADBLMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxGDAWBgoJkiaJk/IsZAEZ
# FghnYXRld2F5MjEYMBYGA1UEAxMPZ2F0ZXdheTItREMxLUNBMB4XDTIwMDMzMDE4
# NTMzN1oXDTIyMDMzMDE5MDMzN1owXzEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRgw
# FgYKCZImiZPyLGQBGRYIZ2F0ZXdheTIxFjAUBgNVBAsMDXhfUkFNQ08gVXNlcnMx
# FDASBgNVBAMTC1phY2sgQWNrbGluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
# CgKCAQEAyqxi1+VWYCKKnVJJUitGku9RmlelOhbrUqzfd5iKJyHiX/xdZ4tBlPbx
# SBmK7y3gY37dnWy5r1ldK8/91DHuNDJ3ZWeJzz4WHsxPRXqM0hsRXVBQ8JzOtWq+
# v2Jr1UeZvTt97LFBs6BhfE0NGU4M9dYxzLiiNoq9w6P3NNDrmKn0Sri7MkMGpiml
# ZK/T5stNL0Hu/DQWInvMHXonUlm/CB1XUqandwY8nD7vBLdLlChzcpj1ohADt0wN
# h1y/OD7WfVrSARL6pBuDKC2M+bSXn6QH34IDQoQqA5/Nmbt6HfJJqW94fSAZQIi/
# uWy3rljxGEKa8pJPcoPlEuBEqzMhJQIDAQABo4ICizCCAocwPAYJKwYBBAGCNxUH
# BC8wLQYlKwYBBAGCNxUIg9eWden/aIT1kSeHi9Qggb3FWCSDvudQgofITgIBZAIB
# AzATBgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwGwYJKwYBBAGC
# NxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUff4W+40vEksxMH/vm1yPd3xn
# gSgwHwYDVR0jBBgwFoAU3+5/2AdRzcHHVJLRSfrYln47fpUwgcwGA1UdHwSBxDCB
# wTCBvqCBu6CBuIaBtWxkYXA6Ly8vQ049Z2F0ZXdheTItREMxLUNBLENOPWRjMSxD
# Tj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049
# Q29uZmlndXJhdGlvbixEQz1nYXRld2F5MixEQz1sb2NhbD9jZXJ0aWZpY2F0ZVJl
# dm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9p
# bnQwgcQGCCsGAQUFBwEBBIG3MIG0MIGxBggrBgEFBQcwAoaBpGxkYXA6Ly8vQ049
# Z2F0ZXdheTItREMxLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
# cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWdhdGV3YXkyLERDPWxv
# Y2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9u
# QXV0aG9yaXR5MC8GA1UdEQQoMCagJAYKKwYBBAGCNxQCA6AWDBRaYWNrQUByYW1j
# b21wYW55LmNvbTANBgkqhkiG9w0BAQ0FAAOCAgEAJD+HJbjHz6ofuc6evcAKOarY
# xjYosU9lh6bxjGERtqhkTYwNGdq+JN5HiPFb/rH0slUP31TS3VCjGzB2AUOnKgAC
# //1/nInKZe1vKtbD0UohcvHgSBryvzcoVFtybmJgH87vKGNuzO3WRQWEGDTwXz6b
# hIx+alReoCrQEmuoC5B6jGuNRDV7ZcOkgwEUVlKLPBQ5MfwoDcO3dsXpXwQWweh4
# X/HWk4Osn4dyCW25XuBi9xMXduphyI3qDInLa7cMkdX3k7Mq8qqb35voLGeKYQbi
# 1RYSCjHeoHYVNNctdw/GBS4TccSr0pdfDRhHey08/wm4rSDQOed4T4cmTrtLly9s
# mvh39eCGXIfr6oh9QLBrvrIoSgCeDpl3T0Oc0cuJUIS04sWUyDkiWGwk2vSDsbma
# VS/cv/4Ghvn0sVT6vaOrHfo3J/adU2KUuMmCWF0tz2zSmF03RoqGmhq1Zrur5Wkz
# rkWNSD/GRldI5BIHzGZCo9/B61WtFESEsq57YzUuqTRkhZqeTdncPwMd7OenxanK
# YYmI7ohaMlD8hkF/4nbNQQUmaiAagPZ7WEeo5ITnFasvc+1r0ypNSjPV0Hi3jBiT
# eVQYWeBuG9btHcZ4j0hgH1lInrfKXL8SY1bafB3Z+0knowfwld7mrdYRYLbeSQPL
# 9K2lx6N9socYOTOdYh4xggIDMIIB/wIBATBiMEsxFTATBgoJkiaJk/IsZAEZFgVs
# b2NhbDEYMBYGCgmSJomT8ixkARkWCGdhdGV3YXkyMRgwFgYDVQQDEw9nYXRld2F5
# Mi1EQzEtQ0ECExoAAACrDky7WaJ0ddAAAAAAAKswCQYFKw4DAhoFAKB4MBgGCisG
# AQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFPVP
# nZGCBAOLwgQcsBsPaQ/s607qMA0GCSqGSIb3DQEBAQUABIIBAAPFGEAP/aNUPgz6
# bI0XGBkWpdzQHN6dX2M+buH4FT0tiajA30BD1JAOiwcDpCS66Q3jSXiWupzyv5mQ
# EJr3ik5Y/ujz5auBU5IRVhb/9UfGcGFhv3nZjwTqCk9YFxX1EJzjiQ4s/WHJ2IaU
# 0+cg+ltVp4edQ1OBtghqV9MoTFS6sDT568JrjmDm29MNYTyrR8Jzk+GpA0VWMYwO
# jfD6Qphi2ClHfR3KUBMNrMSBVmRX6H9cPDPCLWrM3YQ/CIv5q8heIuUm7zH2PKgJ
# FNTk8RttfwAG0bY6orXsKDzNqCRgKBNcbBrNi6HDMn8WNMo9ajJENPJ21l/zOfo8
# YH9LxJc=
# SIG # End signature block
